# Generated by Django 4.1.1 on 2022-12-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountone',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AccountTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_left_child', models.BooleanField(default=False)),
                ('is_right_child', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child', to='treedata.accounttwo')),
            ],
        ),
    ]
