# Generated by Django 4.1.1 on 2022-12-10 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treedata', '0002_alter_accountone_email_accounttwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttwo',
            name='is_left_child',
        ),
        migrations.RemoveField(
            model_name='accounttwo',
            name='is_right_child',
        ),
        migrations.RemoveField(
            model_name='accounttwo',
            name='parent',
        ),
        migrations.AddField(
            model_name='accounttwo',
            name='left_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='left_parent', to='treedata.accounttwo'),
        ),
        migrations.AddField(
            model_name='accounttwo',
            name='right_child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='right_parent', to='treedata.accounttwo'),
        ),
    ]
